# Generated by Django 3.2 on 2024-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobai',
            name='roles',
            field=models.JSONField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobai',
            name='skill',
            field=models.JSONField(max_length=30, null=True),
        ),
    ]
