# Generated by Django 3.2 on 2024-08-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_auto_20240801_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobai',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
