# Generated by Django 3.2 on 2024-08-01 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_jobai_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobai',
            name='skill',
        ),
        migrations.AddField(
            model_name='jobai',
            name='skills',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobai',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='healthcare.category'),
        ),
        migrations.AlterField(
            model_name='jobai',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobai',
            name='roles',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='healthcare.department'),
        ),
        migrations.AlterField(
            model_name='jobai',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_ai', to='healthcare.department'),
        ),
        migrations.DeleteModel(
            name='Development',
        ),
    ]
